// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClWQq1jhBsEL5yF6EVdtLEc4hE0BZmlt0',
    appId: '1:508531660846:web:fb60136c2334e5bd1da7bf',
    messagingSenderId: '508531660846',
    projectId: 'ithubmobile',
    authDomain: 'ithubmobile.firebaseapp.com',
    storageBucket: 'ithubmobile.firebasestorage.app',
    measurementId: 'G-S6QTH9X9NR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVLdadTqWcCYCPQ_JjWlQ14_SaIFi1Eqc',
    appId: '1:508531660846:android:24026da5780c7fdc1da7bf',
    messagingSenderId: '508531660846',
    projectId: 'ithubmobile',
    storageBucket: 'ithubmobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwF3qt7qRLnS2On2gweYnZgMdLVRaVsgg',
    appId: '1:508531660846:ios:f67ef67bff0e3a371da7bf',
    messagingSenderId: '508531660846',
    projectId: 'ithubmobile',
    storageBucket: 'ithubmobile.firebasestorage.app',
    iosBundleId: 'com.example.ithubmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwF3qt7qRLnS2On2gweYnZgMdLVRaVsgg',
    appId: '1:508531660846:ios:f67ef67bff0e3a371da7bf',
    messagingSenderId: '508531660846',
    projectId: 'ithubmobile',
    storageBucket: 'ithubmobile.firebasestorage.app',
    iosBundleId: 'com.example.ithubmobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClWQq1jhBsEL5yF6EVdtLEc4hE0BZmlt0',
    appId: '1:508531660846:web:c62bd06369ec85d91da7bf',
    messagingSenderId: '508531660846',
    projectId: 'ithubmobile',
    authDomain: 'ithubmobile.firebaseapp.com',
    storageBucket: 'ithubmobile.firebasestorage.app',
    measurementId: 'G-XWS68ZFT7F',
  );
}
